In [2]:
import numpy as np
import json
import nbimporter
from PicLocating import RGB_location
from coord_transform import position_to_world_coordinate,rotate_vector_to_world_coordinate


In [104]:
def direction_vector_from_camera(CamName,image):
    #read orientation and pixelVector from json
    with open('CamID.json', 'r') as file:
        cameras = json.load(file)
    for camera in cameras:
        if (camera.get("name")) == CamName:
            pV=camera.get('pixelVector')
            CamLoca=camera.get('location')
            CamOrien_X=camera.get('orientation_X')
            CamOrien_Y=camera.get('orientation_Y')
            CamOrien_Z=camera.get('orientation_Z')
            print(CamLoca)
    
    #find point by PicLocating and find real world direction vector
    RGB=RGB_location(image)
    print(type(RGB[0][0]))
    print(type(pV[0]))
          
    pV[0]=RGB[0][0]*pV[0]
    pV[1]=RGB[0][1]*pV[1]
    print(pV)
    
    #convert to world coordinate
    direction_vector=rotate_vector_to_world_coordinate(pV, CamOrien_X, CamOrien_Y, CamOrien_Z)

    A=(np.eye(3)-direction_vector@(direction_vector.T))
    P=A@CamLoca
    print(A)
    print(P)
                                                       
    return direction_vector,A,P

In [106]:
RGB=RGB_location('RGBcalibration.jpeg')[0]

Mean position of red pixels (R): (1191, 520)
Mean position of green pixels (G): (1190, 584)
Mean position of blue pixels (B): (1238, 522)


In [108]:
V,A,P=direction_vector_from_camera("EricsPad",'RGBcalibration.jpeg')

[-35.53657575548585, 9.026509676087638, -23.512174593042428]
Mean position of red pixels (R): (1191, 520)
Mean position of green pixels (G): (1190, 584)
Mean position of blue pixels (B): (1238, 522)
<class 'float'>
<class 'float'>
[0.21738288811459544, -0.06796239837398374, 1]
[[ 0.02798256 -0.97201744 -0.97201744]
 [-0.97201744  0.02798256 -0.97201744]
 [-0.97201744 -0.97201744  0.02798256]]
[13.08591464 57.64900007 25.1103158 ]


In [110]:
antiA=np.linalg.inv(A)
print(antiA@P)

[-35.53657576   9.02650968 -23.51217459]
